RecipeQA/RecipeQA/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('AllRecipes.urls')),
]

ShopXen/ShopXen/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Xen.urls')),
]

urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ShopXen/Xen/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', chatbot, name='chatbot'),
    path('chat', chathistory, name='chat'),
    path('delchat', delchat, name='delchat'),

    path('cat', home, name='home'),
    path('cat/<int:category_id>', product_detail, name='product_detail'),
    path('product/<int:product_id>', preSales, name='preSales'),

]

ShopXen/Xen/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import User


class ChatHistory(models.Model):
    user_query = models.JSONField(default=list)
    bot_response = models.JSONField(default=list)

    def add_user_query(self, query):
        self.user_query.append(query)
        self.save()

    def add_bot_response(self, response):
        self.bot_response.append(response)
        self.save()

    def histoy(self):
        chat=[]

        for i in range(len(self.user_query)):
            chat.append({'User':self.user_query[i], 'Bot':self.bot_response[i]})

        return chat

class Category(models.Model):
    category_id = models.AutoField(primary_key=True)
    category_name = models.CharField(max_length=255)
    parent_category = models.ForeignKey('self', on_delete=models.SET_NULL, null=True, blank=True)
    gimage = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.category_name

class Product(models.Model):
    product_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255, null=False, blank=False)
    warranty_period_months = models.PositiveIntegerField()
    return_period_days = models.PositiveIntegerField()
    discount_percentage = models.DecimalField(max_digits=5, decimal_places=2)
    feature_list = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    colors = models.CharField(max_length=255)
    weight_grams = models.PositiveIntegerField()
    image_link = models.URLField()
    brand = models.CharField(max_length=255)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)


    def __str__(self):
        return self.name

    @classmethod
    def product(cls, name):
        try:
            return cls.objects.get(name = name)
        except Exception :
            return None
'''
class Product(models.Model):
    product_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255, null=False, blank=False)
    warranty_period_months = models.PositiveIntegerField()
    return_period_days = models.PositiveIntegerField()
    discount_percentage = models.DecimalField(max_digits=5, decimal_places=2)
    feature_list = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    colors = models.CharField(max_length=255)
    weight_grams = models.PositiveIntegerField()
    image_link = models.URLField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)


    def __str__(self):
        return self.name

    @classmethod
    def product(cls, name):
        try:
            return cls.objects.get(name = name)
        except Exception :
            return None

class Product(models.Model):
    product_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=150, null=False, blank=False)
    description = models.TextField(null=False, blank=False)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Variants(models.Model):
    variant_id = models.AutoField(primary_key=True)
    variant = models.CharField(max_length=50)
    image = models.ImageField(null=True, blank=True)
    brand = models.CharField(max_length=255)

class VariantValue(models.Model):
    value_id = models.AutoField(primary_key=True)
    variant_id = models.ForeignKey(Variants, on_delete=models.SET_NULL, null=True)
    value = models.CharField(max_length=50)

class ProductVariants(models.Model):
    product_variants_id = models.AutoField(primary_key=True)
    product_id = models.ForeignKey(Product, on_delete=models.CASCADE)
    variant = models.ForeignKey(Variants, on_delete=models.SET_NULL, null=True)
    sku = models.CharField(max_length=50)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self) -> str:
        return 'self.variant'

class Specification(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    specification_name = models.CharField(max_length=255)
    specification_value = models.TextField()
'''

class Review(models.Model):
    reviews = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE) 
    rating = models.PositiveIntegerField()
    comment = models.TextField()
    date_posted = models.DateTimeField(auto_now_add=True)
####################################################################################################
 
####################################################################################################
class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=15, null=True)
    email = models.TextField()
    phone_number = models.CharField(max_length=15, null=True,)

    def __str__(self) -> str:
        return self.name


class Cart(models.Model):
    cart_id = models.AutoField(primary_key=True)
    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return f'Cart {self.cart_id} {self.customer_id.username}'

class Wishlist(models.Model):
    wish_id = models.AutoField(primary_key=True)
    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

class Order(models.Model):
    order_id = models.AutoField(primary_key=True)
    customer_id = models.ForeignKey(User, on_delete=models.CASCADE)
    payment = models.ForeignKey('Payment', on_delete=models.SET_NULL, null=True)
    shipment = models.ForeignKey('Shipment', on_delete=models.SET_NULL, null=True)
    order_data = models.DateTimeField(auto_now_add=True)
    total_price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self) -> str:
        return f"Order {self.order_id} - {self.customer_id}"
    
class Order_item(models.Model):
    item_id = models.AutoField(primary_key=True)
    order_id = models.ForeignKey(Order,on_delete=models.CASCADE )
    product_id = models.ForeignKey(Product, on_delete=models.CASCADE)
    item_price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField()

    def __str__(self) -> str:
        return f"{self.product_id.name} - {self.item_price}"
    
class Payment(models.Model):
    PAYMENT_CHOICES = (
        ('credit_card', 'Credit Card'),
        ('paypal', 'PayPal'),
        ('cash', 'Cash'),
    )
    payment_id = models.AutoField(primary_key=True)
    payment_type = models.CharField(max_length=20, choices=PAYMENT_CHOICES)
    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2)  
    
    def __str__(self):
        return f"Payment {self.payment_id} - {self.customer.username} - {self.payment_type}"

class Shipment(models.Model):
    Shipment_id = models.AutoField(primary_key=True)
    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    address = models.TextField()
    city = models.CharField(max_length=255)
    country = models.CharField(max_length=255)
    zip = models.CharField(max_length=20)

    def __str__(self):
        return f"Shipment {self.Shipment_id} - {self.customer.username} - {self.address}, {self.city}, {self.country} {self.zip}"

ShopXen/Xen/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404
from .models import *
import pickle
import nltk
from nltk.tokenize import word_tokenize
from nltk.util import ngrams
import string
import urllib.parse
import json
import random
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

from nltk import pos_tag
from sklearn.feature_extraction import DictVectorizer
from nltk.stem import PorterStemmer
import json
import pickle  # Unchanged
import urllib.parse
import random
import string
import nltk
import numpy as np
from nltk.util import ngrams
from nltk.tokenize import word_tokenize
from nltk import pos_tag
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from nltk.stem import PorterStemmer
from sklearn.feature_extraction import DictVectorizer
from sklearn.ensemble import RandomForestClassifier
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from .models import ChatHistory  # Import your ChatHistory model

# Load your model
with open('your_model.pickle', 'rb') as model_file:
    chatmodel = pickle.load(model_file)

# Load other resources
with open('vectorizer.pickle', 'rb') as vectorizer_file:
    vectorizer = pickle.load(vectorizer_file)

with open('train_data.json', 'r') as json_file:
    data = json.load(json_file)

# i don't konw
sim_tfidfile = open('similarity_tfidf.pickle', 'rb')
sim_tfidf = pickle.load(sim_tfidfile)

# i don't konw
pat_tfidfile = open('tfidf_matrix.pkl', 'rb')
pat_tfidf = pickle.load(pat_tfidfile)

chatbot_responses = {}
for item in data:
    chatbot_responses[item['tag']] = item['responses']


# Unchanged check_similarity function
def check_similarity(query):
    query_ = []
    stemmer = PorterStemmer()
    query = query.split(' ')
    for pattern in query:
        pat = ''
        pat += stemmer.stem(pattern.lower())+' '
        
        query_.append(' '.join(word_tokenize(pat)))
    g = sim_tfidf
    uqv = sim_tfidf.transform(query).toarray()
    cosine_similarities = cosine_similarity(uqv, pat_tfidf).flatten()
  
    idxs = np.where(cosine_similarities>0.3)
    if len(list(idxs[0]))==0:
        return -1

    return 1

import json

# Function to load product data from the database file
def load_product_data(file_path):
    with open(file_path, 'r') as file:
        product_data = json.load(file)
    return product_data

# Load product data from the database
product_data = load_product_data('product_fixture.json')

# Function to retrieve product information from the database
def get_product_info(product_name, predicted_tag):
    for product in product_data:
        if product["fields"]["name"] == product_name:
            if predicted_tag == "product_warranty":
                return {"product_warranty": product["fields"]["warranty_period_months"]}
            elif predicted_tag == "product_return":
                return {"product_return": product["fields"]["return_period_days"]}
            elif predicted_tag == "product_discount":
                return {"product_discount": product["fields"]["discount_percentage"]}
            elif predicted_tag == "product_features":
                return {"product_features": product["fields"]["feature_list"]}
            elif predicted_tag == "product_price":
                return {"product_price": product["fields"]["price"]}
            elif predicted_tag == "product_colors":
                return {"product_colors": product["fields"]["colors"]}
            elif predicted_tag == "product_weight":
                return {"product_weight": product["fields"]["weight_grams"]}
            elif predicted_tag == "product_images":
                return {"product_images": product["fields"]["image_link"]}
            # Add more conditions for other tags as needed
    print("No item")
    return {}

def read_training_data(file_path):
    with open(file_path, 'r') as file:
        training_data = json.load(file)
    return training_data
training_data = read_training_data('train_data.json')

# Function to get the appropriate response based on the predicted_tag
def get_response(predicted_tag, product_name=None):
    for data in training_data:
        if data["tag"] == predicted_tag:
            product_info = get_product_info(product_name, predicted_tag)
            response = data["responses"][0].format(product_name=product_name, **product_info)
            return response
    return "Sorry, I don't have a response for that."

# Done
def preprocess_text(text):
    tokens = nltk.word_tokenize(text)

    tokens = [word.lower() for word in tokens]

    stop_words = set(nltk.corpus.stopwords.words('english'))
    tokens = [word for word in tokens if word not in stop_words and word not in string.punctuation]

    bigrams_list = list(ngrams(tokens, 1))  # '1' n-gram size

    lemmatizer = nltk.stem.WordNetLemmatizer()
    tokens = [' '.join(bigram) for bigram in bigrams_list]

    return tokens

# Done
def extract_pos_tags(text):
    tokens = word_tokenize(text)
    pos_tags = pos_tag(tokens)
    return [tag for _, tag in pos_tags]

# Done
def preprocess_text_to_features(text, n=1):
    preprocessed_text = preprocess_text(text)
    feature_dict = {' '.join(bigram): True for bigram in preprocessed_text}
    
    # Extract POS tags and add them as features
    pos_tags = extract_pos_tags(text)
    for tag in pos_tags:
        feature_dict[tag] = True
    
    return feature_dict

import spacy

# Replace 'path_to_output_directory' with the actual path to your saved model
model_path = "path_to_output_directory"
# Load the trained NER model
nlp = spacy.load(model_path)

def extract_product_name(user_input):
    doc = nlp(user_input)
    product_names = [ent.text for ent in doc.ents if ent.label_ == "PRODUCT"]
    return product_names

user_context = {}

@csrf_exempt
def chathistory(request):
    response = ''
    body = request.body
    decoded_str = urllib.parse.unquote(body.decode('utf-8'))
    query = decoded_str.split('=')[1]
    response = 'Sorry, but I cannot help you with that'
    global user_context

    # Check for similarity
    if check_similarity(query) != -1:
        # like get_tag function that returns the predicted_tag
        feature_dict = preprocess_text_to_features(query)
        pos_tags = extract_pos_tags(query)
        for tag in pos_tags:
            feature_dict[tag] = True
        feature_vector = vectorizer.transform([feature_dict])
        predicted_tag = chatmodel.predict(feature_vector)[0]
        ########
        product_names = extract_product_name(query)

        # flag to save if there is a product name or not
        flag = 1 
        if not product_names:
            flag = 0
            # Try to extract product names from the last query
            last_query = user_context.get("last_query", "")
            product_names = extract_product_name(last_query)
            print("there is no products name")
         
        responses = []
        # Iterate over product_names and retrieve product information
        for product_name in product_names:
            print(f"predicted_tag {predicted_tag}")
            response = get_response(predicted_tag, product_name)
            print(response)
            responses.append(response)

        if responses:
            final_response = "\n".join(responses)
        else:
            final_response = f"Sorry, I couldn't find information about {predicted_tag.replace('_', ' ')} for the specified products."

        # Save context for future queries
        if flag != 0:
            user_context["last_query"] = query
        user_context["last_response"] = final_response

        response = final_response
        ch, created =  ChatHistory.objects.get_or_create(pk=1)

    # The rest of your code to save the chat history and return the response

    ch.add_user_query(query)
    ch.add_bot_response(response)
    ch = ChatHistory.objects.get(pk=1).histoy()

    text = ''
    for i in ch:
        print(i.keys())
        text += i['User'] + '@' + i['Bot'] + '@'
    return HttpResponse(text)
    

# Unchanged Django views (chatbot, home, product_detail, preSales, delchat)

def chatbot(request):
    ch = ChatHistory.objects.all()
    if ch:
        ch= ch.get(pk=1).histoy()
    return render(request, 'Xen/chatbot.html', {'history':ch})

def home(request):
    category = Category.objects.all()
    return render(request, 'Xen/store.html', {'categories':category})


def product_detail(request, category_id):
    category = Category.objects.get(category_id=category_id)
    products = category.product_set.all() 
    return render(request, 'Xen/product_details.html', {'products':products})


def preSales(request, product_id):
    product = Product.objects.get(product_id=product_id)
    print(product)
    return render(request, 'Xen/presales.html', {'product':product})

def delchat(request):
    d = ChatHistory.objects.get(pk=1)
    d.delete()
    return HttpResponse('')

templates/Xen/cart.html
<h1>cart</h1>

templates/Xen/chatbot.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <title>Text Input with Submit Button</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
    <script src="{% static 'js/send_receive.js' %}"></script>
</head>
<body>
    <form method="post">
        {% csrf_token %}

        <label for="userInput">Enter Text:</label>
        <input type="text" id="input" name="userInput" required>
        <button id="query">Submit</button>
    </form>
    <button id="delete">delete chat</button>

    <div id="chat">
        
    {% for chat in history %}
    <h3> {{ chat.User }}</h3>
    <h3> {{ chat.Bot }}</h3>
    <hr>
    {% endfor %}
</div>

</body>
 
</html>

templates/Xen/checkout.html
  {% extends 'Xen/main.html' %}
  {% load static %}
  
  {% block content %}
  <h1>Checkout</h1>
  {% endblock content %}

templates/Xen/main.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>ShopXen</title>
	<script src="{% static 'js/script.js' %}"></script>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	<meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
        integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>

	<nav class="navbar navbar-expand-lg navbar-light bg-light">
	  <a class="navbar-brand" href="#">ShopXen</a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav mr-auto">
	      <li class="nav-item active">
	        <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
	      </li>

	    </ul>
	    <form class="form-inline my-2 my-lg-0">
	      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
	      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
	    </form>
	  </div>
	</nav>

     <div class="container">
            <br>
            {% block content %}


            {% endblock content %}
         </div>


	<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>

	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

templates/Xen/presales.html
{% extends 'Xen/main.html' %}
{% load static %}
{% block content%}
    <div class="product-detail">
        <div class="product-image">
            <img class="thumbnail" src="{{ product.image_link }}" style="width:200px; height:200px;" >
        </div>
        <div class="product-info">
            <h1>{{ product }}</h1>
            <p>{{ product.description }}</p>
        </div>
        <div class="add-to-cart">
                {% csrf_token %}
                <button type="submit">Add to Cart</button>
            </form>
        </div>
    </div>
    Technical Details
    {{product}}
        {% for spec in product.specification_set.all %}
        <li>
            <p><h5>{{spec.specification_name}} : {{ spec.specification_value }}</p></h5>
            <hr>
        </li>
        {% empty %}
            <li>No reviews yet.</li>
        {% endfor %}
    <div class="product-reviews">
        <h2>Customer Reviews</h2>
        <ul>
            {% for review in product.review_set.all %}
                <li>
                    <p>Rating: {{ review.rating }}</p>
                    <p>Comment: {{ review.comment }}</p>
                    <p>Posted by: {{ review.user.username }}</p>
                </li>
            {% empty %}
                <li>No reviews yet.</li>
            {% endfor %}
        </ul>
    </div>

{% endblock content%}

templates/Xen/product_details.html
{% extends 'Xen/main.html' %}
{% load static %}
{% block content%}
    <div class="row">
    
        {% for product in products %}

        
        <div class="col-lg-4">
                {{ product.feature_list }}<br>
                <div class="box-element product">
                    
                    <a href="{% url 'preSales' product.product_id %}">
                        <h6><strong>{{ product }}</strong></h6>

                        
                        <strong>Discount:</strong> {{ product.discount_percentage }}%<br>
                            <img class="thumbnail" src="{{ product.image_link }}" >

                        <li>
                            Price: ${{ product.price }}
                        </li>
                        <small style="color: blue;">Shop now</small>
                    </a>
                </div>
                
            </div>

               
            {% endfor %}
                         
            </div>
{% endblock content%}

templates/Xen/product_info.html
{% extends 'Xen/main.html' %}

{% load static %}

{% block content %}
    <h2>{{ pname }}</h2>
{% endblock content %}

templates/Xen/store.html
{% extends 'Xen/main.html' %}
{% load static %}
{% block content%}

    <div class="row">
        {% for category in categories %}
            <div class="col-lg-4">
                <div class="box-element product">
                    
                    <a href="{% url 'product_detail' category.category_id %}">
                        <h6><strong>{{ category }}</strong></h6>
                        <img class="thumbnail" src="{{ category.gimage.url }}" >
                        <small style="color: blue;">Shop now</small>
                    </a>
                </div>
                
            </div>

               
                         
            {% endfor %}
        </div>
{% endblock content%}